export const data: DataTypes = {
  crewInfo: [
    {
      crew_id: 1,
      car_mark: "Chevrolet",
      car_model: "Lacetti",
      car_color: "синий",
      car_number: "Е234КУ",
      driver_name: "Деточкин",
      driver_phone: "7788",
      lat: 56.853601,
      lon: 53.198869,
    },
    {
      crew_id: 2,
      car_mark: "Hyundai",
      car_model: "Solaris",
      car_color: "белый",
      car_number: "Ф567АС",
      driver_name: "Петров",
      driver_phone: "8899",
      lat: 56.856146,
      lon: 53.202022,
    },
    {
      crew_id: 3,
      car_mark: "Chevrolet",
      car_model: "Astra",
      car_color: "белый",
      car_number: "Ф567АС",
      driver_name: "Иванов",
      driver_phone: "8899",
      lat: 56.857897,
      lon: 53.210717,
    },
    {
      crew_id: 4,
      car_mark: "Nissan",
      car_model: "Almera",
      car_color: "серый",
      car_number: "Ф567АС",
      driver_name: "Алексеев",
      driver_phone: "8899",
      lat: 56.865235,
      lon: 53.209427,
    },
    {
      crew_id: 5,
      car_mark: "Skoda",
      car_model: "Octavia",
      car_color: "бежевый",
      car_number: "Ф567АС",
      driver_name: "Александров",
      driver_phone: "8899",
      lat: 56.872299,
      lon: 3.217708,
    },
    {
      crew_id: 6,
      car_mark: "Mazda",
      car_model: "CX-9",
      car_color: "красный",
      car_number: "Ф567АС",
      driver_name: "Семенов",
      driver_phone: "8899",
      lat: 56.878015,
      lon: 53.216509,
    },
  ],
  recommendedCrew: [],
  myOrders: undefined,
  myAddress: undefined,
};
